## 非同期処理で必要になるローディングとエラーの処理

- 外部パッケージを使わず、基本形で記述してみる
- ローディング用とエラー用の useState を用意して、getPosts();の中で setLoading して、そこで状態を変えていく
- return 文の中で、ローディングとエラーの際の表示させる

### まずは、ローディングから
> const [posts, setPosts] = useState([]);の次に
```js
const [loading, setLoading] = useState(true);
```

> と引数を true にして、ローディングを表示させる

```js
{
  post.length > 0 ? (
    <ol>
      {posts.map((post) => {
        return <li key={post.id}>{post.title}</li>;
      })}
    </ol>
  ) : null
}
```

の部分を

```js
{
  loading ? (
    <div>ローディング中</div>
  ) : posts.length > 0 ? (
    <ol>
      {posts.map((post) => {
        return <li key={post.id}>{post.title}</li>;
      })}
    </ol>
  ) : null
}
```

- とすると、ブラウザに"ローディング中"が表示される
  > 次に、API を取得した後は、false にしたいので

```js
setPosts(json);
```

> の下に、

```js
setLoading(false);
```

> と記述する。
> ここまでの記述では、データがない時には null で何も表示されないので、
> データがないときは、データがありませんと表示されるようにする

- null のところを次に書き換える

```js
<div>データは空です</div>
```

### 次はエラー状態の表示

```js
const [loading, setLoading] = useState(true);
```

> の下に

```js
const [error, setError] = useState(null);
```

> を記述。
> 次に、非同期処理なのでよく行われるトライ、キャッチ文でエラーのハンドリングを行う。
- const getPosts = useCallback(async () => {の次に
```js
try {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");

  const json = await res.json();
  setPosts(json);
} catch (error) {
  setError(error);
}
setLoading(false);
```

> と記述すると、データが取得できなかった時にも"データは空"と表示されるので、取得できなかったときは、"エラーが発生したため、データの取得に失敗しました。"と表示させるように記述する。

```js
try {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  if (!res.ok) {
    throw new Error("エラーが発生したため、データの取得に失敗しました。");
  }
  const json = await res.json();
  setPosts(json);
} catch (error) {
  setError(error);
}
```

> これで、setError(error);の error のなかにエラーメッセージが入っているので、これをリターン文で表示させる。

```js
return (
  {loading ? (
    <div>ローディング中</div>
  ) : error ? (
    <div>{error.message}</div>
  ) : posts.length > 0 ? (
  <ol>
    {posts.map((post) => {
      return <li key={post.id}>{post.title}</li>;
    })}
  </ol>
  ) : (
    <div>データは空です</div>
  )}

);
```

> とすることで、エラーメッセージを表示できる。

### ここまでの記述をコンポーネントにまとめる。

- component フォルダの下層に Posts フォルダを作成
- その中に、index.jsx ファイルを作成
- pages 内の index.jsx をコピーして、Posts の index.jsx にペースト
- 不必要な部分を削除すると

```js
import { useCallback, useEffect, useState } from "react";

export const Posts = () => {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const getPosts = useCallback(async () => {
    try {
      const res = await fetch("https://jsonplaceholder.typicode.com/posts");
      if (!res.ok) {
        throw new Error("エラーが発生したため、データの取得に失敗しました。");
      }
      const json = await res.json();
      setPosts(json);
    } catch (error) {
      setError(error);
    }
    setLoading(false);
  }, []);
  useEffect(() => {
    getPosts();
  }, [getPosts]);
  return (
    <div>
      {loading ? (
        <div>ローディング中</div>
      ) : error ? (
        <div>{error.message}</div>
      ) : posts.length > 0 ? (
        <ol>
          {posts.map((post) => {
            return <li key={post.id}>{post.title}</li>;
          })}
        </ol>
      ) : (
        <div>データは空です</div>
      )}
    </div>
  );
};
```

> return 文が冗長なのでリファクタリング

```js
useEffect(() => {
  getPosts();
}, [getPosts]);
if (loading) {
  return <div>ローディング中</div>;
}
if (error) {
  return <div>{error.message}</div>;
}
if (posts.length === 0) {
  return <div>データは空です</div>;
}

return (
  <ol>
    {posts.map((post) => {
      return <li key={post.id}>{post.title}</li>;
    })}
  </ol>
);
```
> pages/index.jsxは
```js
import Head from "next/head";
import { Header } from "src/components/Header";
import { Posts } from "src/components/Posts";
import styles from "src/styles/Home.module.css";

const Home = () => {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
      </Head>
      <Header />
      <Posts/>
    </div>
  );
};

export default Home;
```
> となる
---
- コミット
  - 🚸APIを叩く際のローディング状態エラー状態の管理
